export const PERMISSIONS = {
  DASHBOARD_VIEW: "DASHBOARD_VIEW",

  ACADEMY_VIEW: "ACADEMY_VIEW",
  ACADEMY_UPDATE: "ACADEMY_UPDATE",
  ACADEMY_DELETE: "ACADEMY_DELETE",
  OWNERSHIP_TRANSFER: "OWNERSHIP_TRANSFER",

  STAFF_VIEW: "STAFF_VIEW",
  STAFF_INVITE: "STAFF_INVITE",
  STAFF_UPDATE: "STAFF_UPDATE",
  STAFF_REMOVE: "STAFF_REMOVE",

  PLAYERS_VIEW: "PLAYERS_VIEW",
  PLAYERS_CREATE: "PLAYERS_CREATE",
  PLAYERS_UPDATE: "PLAYERS_UPDATE",
  PLAYERS_DELETE: "PLAYERS_DELETE",

  GUARDIANS_VIEW: "GUARDIANS_VIEW",
  GUARDIANS_CREATE: "GUARDIANS_CREATE",
  GUARDIANS_UPDATE: "GUARDIANS_UPDATE",
  GUARDIANS_DELETE: "GUARDIANS_DELETE",

  TEAMS_VIEW: "TEAMS_VIEW",
  TEAMS_CREATE: "TEAMS_CREATE",
  TEAMS_UPDATE: "TEAMS_UPDATE",
  TEAMS_DELETE: "TEAMS_DELETE",
  TEAM_ROSTER_MANAGE: "TEAM_ROSTER_MANAGE",

  COACHES_VIEW: "COACHES_VIEW",
  COACHES_CREATE: "COACHES_CREATE",
  COACHES_UPDATE: "COACHES_UPDATE",
  COACHES_DELETE: "COACHES_DELETE",
  COACH_ASSIGNMENTS_MANAGE: "COACH_ASSIGNMENTS_MANAGE",

  TRAINING_VIEW: "TRAINING_VIEW",
  TRAINING_CREATE: "TRAINING_CREATE",
  TRAINING_UPDATE: "TRAINING_UPDATE",
  TRAINING_DELETE: "TRAINING_DELETE",

  ATTENDANCE_VIEW: "ATTENDANCE_VIEW",
  ATTENDANCE_MANAGE: "ATTENDANCE_MANAGE",

  DRILLS_VIEW: "DRILLS_VIEW",
  DRILLS_CREATE: "DRILLS_CREATE",
  DRILLS_UPDATE: "DRILLS_UPDATE",
  DRILLS_DELETE: "DRILLS_DELETE",

  MATCHES_VIEW: "MATCHES_VIEW",
  MATCHES_CREATE: "MATCHES_CREATE",
  MATCHES_UPDATE: "MATCHES_UPDATE",
  MATCHES_DELETE: "MATCHES_DELETE",
  MATCH_SQUAD_MANAGE: "MATCH_SQUAD_MANAGE",
  MATCH_EVENTS_MANAGE: "MATCH_EVENTS_MANAGE",

  PERFORMANCE_VIEW: "PERFORMANCE_VIEW",
  PERFORMANCE_MANAGE: "PERFORMANCE_MANAGE",

  SCOUTING_VIEW: "SCOUTING_VIEW",
  SCOUTING_MANAGE: "SCOUTING_MANAGE",

  CALENDAR_VIEW: "CALENDAR_VIEW",
  CALENDAR_MANAGE: "CALENDAR_MANAGE",

  NOTIFICATIONS_VIEW: "NOTIFICATIONS_VIEW",
  NOTIFICATIONS_MANAGE: "NOTIFICATIONS_MANAGE",

  PAYMENTS_VIEW: "PAYMENTS_VIEW",
  PAYMENTS_MANAGE: "PAYMENTS_MANAGE",

  EXPENSES_VIEW: "EXPENSES_VIEW",
  EXPENSES_MANAGE: "EXPENSES_MANAGE",

  FINANCE_VIEW: "FINANCE_VIEW",

  REPORTS_SPORTS_VIEW: "REPORTS_SPORTS_VIEW",
  REPORTS_FINANCE_VIEW: "REPORTS_FINANCE_VIEW",

  SEASONS_VIEW: "SEASONS_VIEW",
  SEASONS_MANAGE: "SEASONS_MANAGE",

  SETTINGS_VIEW: "SETTINGS_VIEW",
  SETTINGS_MANAGE: "SETTINGS_MANAGE",

  TACTICS_VIEW: "TACTICS_VIEW",
  TACTICS_MANAGE: "TACTICS_MANAGE",

  KNOWLEDGE_VIEW: "KNOWLEDGE_VIEW",
  KNOWLEDGE_MANAGE: "KNOWLEDGE_MANAGE",

  DOCUMENTS_VIEW: "DOCUMENTS_VIEW",
  DOCUMENTS_MANAGE: "DOCUMENTS_MANAGE",

  MEDICAL_VIEW: "MEDICAL_VIEW",
  MEDICAL_MANAGE: "MEDICAL_MANAGE",

  FACILITIES_VIEW: "FACILITIES_VIEW",
  FACILITIES_MANAGE: "FACILITIES_MANAGE",

  SUBSCRIPTION_VIEW: "SUBSCRIPTION_VIEW",
  SUBSCRIPTION_MANAGE: "SUBSCRIPTION_MANAGE",
} as const;

export type Permission =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ACADEMY_ROLES = {
  OWNER: "OWNER",
  ADMIN: "ADMIN",
  SPORTS_DIRECTOR: "SPORTS_DIRECTOR",
  HEAD_COACH: "HEAD_COACH",
  COACH: "COACH",
  ASSISTANT_COACH: "ASSISTANT_COACH",
  FINANCE: "FINANCE",
  RECEPTIONIST: "RECEPTIONIST",
  MEMBER: "MEMBER",
} as const;

export type AcademyRoleName =
  (typeof ACADEMY_ROLES)[keyof typeof ACADEMY_ROLES];

export const ROLE_LABELS: Record<AcademyRoleName, string> = {
  OWNER: "Pronar",
  ADMIN: "Administrator",
  SPORTS_DIRECTOR: "Drejtor sportiv",
  HEAD_COACH: "Trajner kryesor",
  COACH: "Trajner",
  ASSISTANT_COACH: "Ndihmës trajner",
  FINANCE: "Financa",
  RECEPTIONIST: "Recepsion",
  MEMBER: "Anëtar",
};

const ALL_PERMISSIONS =
  Object.values(PERMISSIONS) as Permission[];

export const ROLE_PERMISSIONS: Record<
  AcademyRoleName,
  readonly Permission[]
> = {
  OWNER: ALL_PERMISSIONS,

  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.ACADEMY_VIEW,
    PERMISSIONS.ACADEMY_UPDATE,

    PERMISSIONS.STAFF_VIEW,
    PERMISSIONS.STAFF_INVITE,
    PERMISSIONS.STAFF_UPDATE,
    PERMISSIONS.STAFF_REMOVE,

    PERMISSIONS.PLAYERS_VIEW,
    PERMISSIONS.PLAYERS_CREATE,
    PERMISSIONS.PLAYERS_UPDATE,
    PERMISSIONS.PLAYERS_DELETE,

    PERMISSIONS.GUARDIANS_VIEW,
    PERMISSIONS.GUARDIANS_CREATE,
    PERMISSIONS.GUARDIANS_UPDATE,
    PERMISSIONS.GUARDIANS_DELETE,

    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_CREATE,
    PERMISSIONS.TEAMS_UPDATE,
    PERMISSIONS.TEAMS_DELETE,
    PERMISSIONS.TEAM_ROSTER_MANAGE,

    PERMISSIONS.COACHES_VIEW,
    PERMISSIONS.COACHES_CREATE,
    PERMISSIONS.COACHES_UPDATE,
    PERMISSIONS.COACHES_DELETE,
    PERMISSIONS.COACH_ASSIGNMENTS_MANAGE,

    PERMISSIONS.TRAINING_VIEW,
    PERMISSIONS.TRAINING_CREATE,
    PERMISSIONS.TRAINING_UPDATE,
    PERMISSIONS.TRAINING_DELETE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.DRILLS_VIEW,
    PERMISSIONS.DRILLS_CREATE,
    PERMISSIONS.DRILLS_UPDATE,
    PERMISSIONS.DRILLS_DELETE,

    PERMISSIONS.MATCHES_VIEW,
    PERMISSIONS.MATCHES_CREATE,
    PERMISSIONS.MATCHES_UPDATE,
    PERMISSIONS.MATCHES_DELETE,
    PERMISSIONS.MATCH_SQUAD_MANAGE,
    PERMISSIONS.MATCH_EVENTS_MANAGE,

    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.PERFORMANCE_MANAGE,

    PERMISSIONS.SCOUTING_VIEW,
    PERMISSIONS.SCOUTING_MANAGE,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,

    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_MANAGE,

    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_MANAGE,

    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_MANAGE,

    PERMISSIONS.FINANCE_VIEW,

    PERMISSIONS.REPORTS_SPORTS_VIEW,
    PERMISSIONS.REPORTS_FINANCE_VIEW,

    PERMISSIONS.SEASONS_VIEW,
    PERMISSIONS.SEASONS_MANAGE,

    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,

    PERMISSIONS.TACTICS_VIEW,
    PERMISSIONS.TACTICS_MANAGE,

    PERMISSIONS.KNOWLEDGE_VIEW,
    PERMISSIONS.KNOWLEDGE_MANAGE,

    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DOCUMENTS_MANAGE,

    PERMISSIONS.MEDICAL_VIEW,
    PERMISSIONS.MEDICAL_MANAGE,

    PERMISSIONS.FACILITIES_VIEW,
    PERMISSIONS.FACILITIES_MANAGE,

    PERMISSIONS.SUBSCRIPTION_VIEW,
  ],

  SPORTS_DIRECTOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.ACADEMY_VIEW,

    PERMISSIONS.STAFF_VIEW,

    PERMISSIONS.PLAYERS_VIEW,
    PERMISSIONS.PLAYERS_CREATE,
    PERMISSIONS.PLAYERS_UPDATE,

    PERMISSIONS.GUARDIANS_VIEW,

    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAMS_CREATE,
    PERMISSIONS.TEAMS_UPDATE,
    PERMISSIONS.TEAM_ROSTER_MANAGE,

    PERMISSIONS.COACHES_VIEW,
    PERMISSIONS.COACHES_CREATE,
    PERMISSIONS.COACHES_UPDATE,
    PERMISSIONS.COACH_ASSIGNMENTS_MANAGE,

    PERMISSIONS.TRAINING_VIEW,
    PERMISSIONS.TRAINING_CREATE,
    PERMISSIONS.TRAINING_UPDATE,
    PERMISSIONS.TRAINING_DELETE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.DRILLS_VIEW,
    PERMISSIONS.DRILLS_CREATE,
    PERMISSIONS.DRILLS_UPDATE,
    PERMISSIONS.DRILLS_DELETE,

    PERMISSIONS.MATCHES_VIEW,
    PERMISSIONS.MATCHES_CREATE,
    PERMISSIONS.MATCHES_UPDATE,
    PERMISSIONS.MATCHES_DELETE,
    PERMISSIONS.MATCH_SQUAD_MANAGE,
    PERMISSIONS.MATCH_EVENTS_MANAGE,

    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.PERFORMANCE_MANAGE,

    PERMISSIONS.SCOUTING_VIEW,
    PERMISSIONS.SCOUTING_MANAGE,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,

    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_MANAGE,

    PERMISSIONS.REPORTS_SPORTS_VIEW,

    PERMISSIONS.SEASONS_VIEW,

    PERMISSIONS.TACTICS_VIEW,
    PERMISSIONS.TACTICS_MANAGE,

    PERMISSIONS.KNOWLEDGE_VIEW,
    PERMISSIONS.KNOWLEDGE_MANAGE,

    PERMISSIONS.DOCUMENTS_VIEW,

    PERMISSIONS.MEDICAL_VIEW,
    PERMISSIONS.MEDICAL_MANAGE,

    PERMISSIONS.FACILITIES_VIEW,
  ],

  HEAD_COACH: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PLAYERS_VIEW,
    PERMISSIONS.PLAYERS_UPDATE,

    PERMISSIONS.GUARDIANS_VIEW,

    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.TEAM_ROSTER_MANAGE,

    PERMISSIONS.COACHES_VIEW,

    PERMISSIONS.TRAINING_VIEW,
    PERMISSIONS.TRAINING_CREATE,
    PERMISSIONS.TRAINING_UPDATE,
    PERMISSIONS.TRAINING_DELETE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.DRILLS_VIEW,
    PERMISSIONS.DRILLS_CREATE,
    PERMISSIONS.DRILLS_UPDATE,

    PERMISSIONS.MATCHES_VIEW,
    PERMISSIONS.MATCHES_CREATE,
    PERMISSIONS.MATCHES_UPDATE,
    PERMISSIONS.MATCH_SQUAD_MANAGE,
    PERMISSIONS.MATCH_EVENTS_MANAGE,

    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.PERFORMANCE_MANAGE,

    PERMISSIONS.SCOUTING_VIEW,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,

    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_MANAGE,

    PERMISSIONS.REPORTS_SPORTS_VIEW,

    PERMISSIONS.SEASONS_VIEW,

    PERMISSIONS.TACTICS_VIEW,
    PERMISSIONS.TACTICS_MANAGE,

    PERMISSIONS.KNOWLEDGE_VIEW,

    PERMISSIONS.DOCUMENTS_VIEW,

    PERMISSIONS.MEDICAL_VIEW,
    PERMISSIONS.MEDICAL_MANAGE,

    PERMISSIONS.FACILITIES_VIEW,
  ],

  COACH: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PLAYERS_VIEW,
    PERMISSIONS.PLAYERS_UPDATE,

    PERMISSIONS.TEAMS_VIEW,

    PERMISSIONS.COACHES_VIEW,

    PERMISSIONS.TRAINING_VIEW,
    PERMISSIONS.TRAINING_CREATE,
    PERMISSIONS.TRAINING_UPDATE,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.DRILLS_VIEW,
    PERMISSIONS.DRILLS_CREATE,
    PERMISSIONS.DRILLS_UPDATE,

    PERMISSIONS.MATCHES_VIEW,
    PERMISSIONS.MATCHES_CREATE,
    PERMISSIONS.MATCHES_UPDATE,
    PERMISSIONS.MATCH_SQUAD_MANAGE,
    PERMISSIONS.MATCH_EVENTS_MANAGE,

    PERMISSIONS.PERFORMANCE_VIEW,
    PERMISSIONS.PERFORMANCE_MANAGE,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,

    PERMISSIONS.NOTIFICATIONS_VIEW,

    PERMISSIONS.REPORTS_SPORTS_VIEW,

    PERMISSIONS.SEASONS_VIEW,

    PERMISSIONS.TACTICS_VIEW,
    PERMISSIONS.TACTICS_MANAGE,

    PERMISSIONS.KNOWLEDGE_VIEW,

    PERMISSIONS.DOCUMENTS_VIEW,

    PERMISSIONS.MEDICAL_VIEW,

    PERMISSIONS.FACILITIES_VIEW,
  ],

  ASSISTANT_COACH: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PLAYERS_VIEW,
    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.COACHES_VIEW,

    PERMISSIONS.TRAINING_VIEW,

    PERMISSIONS.ATTENDANCE_VIEW,
    PERMISSIONS.ATTENDANCE_MANAGE,

    PERMISSIONS.DRILLS_VIEW,

    PERMISSIONS.MATCHES_VIEW,
    PERMISSIONS.MATCH_SQUAD_MANAGE,

    PERMISSIONS.PERFORMANCE_VIEW,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,

    PERMISSIONS.SEASONS_VIEW,

    PERMISSIONS.TACTICS_VIEW,
    PERMISSIONS.KNOWLEDGE_VIEW,

    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.MEDICAL_VIEW,

    PERMISSIONS.FACILITIES_VIEW,
  ],

  FINANCE: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PLAYERS_VIEW,
    PERMISSIONS.GUARDIANS_VIEW,

    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_MANAGE,

    PERMISSIONS.EXPENSES_VIEW,
    PERMISSIONS.EXPENSES_MANAGE,

    PERMISSIONS.FINANCE_VIEW,

    PERMISSIONS.REPORTS_FINANCE_VIEW,

    PERMISSIONS.NOTIFICATIONS_VIEW,

    PERMISSIONS.SUBSCRIPTION_VIEW,
  ],

  RECEPTIONIST: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.PLAYERS_VIEW,
    PERMISSIONS.PLAYERS_CREATE,
    PERMISSIONS.PLAYERS_UPDATE,

    PERMISSIONS.GUARDIANS_VIEW,
    PERMISSIONS.GUARDIANS_CREATE,
    PERMISSIONS.GUARDIANS_UPDATE,

    PERMISSIONS.TEAMS_VIEW,
    PERMISSIONS.COACHES_VIEW,
    PERMISSIONS.TRAINING_VIEW,

    PERMISSIONS.ATTENDANCE_VIEW,

    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.CALENDAR_MANAGE,

    PERMISSIONS.NOTIFICATIONS_VIEW,

    PERMISSIONS.PAYMENTS_VIEW,
    PERMISSIONS.PAYMENTS_MANAGE,

    PERMISSIONS.SEASONS_VIEW,

    PERMISSIONS.DOCUMENTS_VIEW,
  ],

  MEMBER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.CALENDAR_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
  ],
};

export function getRolePermissions(
  role: string
): readonly Permission[] {
  return (
    ROLE_PERMISSIONS[role as AcademyRoleName] ?? []
  );
}

export function hasPermission(
  role: string,
  permission: Permission
): boolean {
  return getRolePermissions(role).includes(permission);
}

export function hasAnyPermission(
  role: string,
  permissions: readonly Permission[]
): boolean {
  return permissions.some((permission) =>
    hasPermission(role, permission)
  );
}

export function hasEveryPermission(
  role: string,
  permissions: readonly Permission[]
): boolean {
  return permissions.every((permission) =>
    hasPermission(role, permission)
  );
}